force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Alpha2__c.field-meta.xml
<CustomField>
    <fullName>Alpha2__c</fullName>
    <label>Alpha2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>DZ</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Alpha3__c.field-meta.xml
<CustomField>
    <fullName>Alpha3__c</fullName>
    <label>Alpha3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Alpha2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFG</fullName>
            </value>
            <value>
                <fullName>ALA</fullName>
            </value>
            <value>
                <fullName>ALB</fullName>
            </value>
            <value>
                <fullName>DZA</fullName>
            </value>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AIA</fullName>
            </value>
            <value>
                <fullName>ATA</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/UN_Code__c.field-meta.xml
<CustomField>
    <fullName>UN_Code__c</fullName>
    <label>UN Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Alpha3__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>248</fullName>
            </value>
            <value>
                <fullName>008</fullName>
            </value>
            <value>
                <fullName>012</fullName>
            </value>
            <value>
                <fullName>016</fullName>
            </value>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>024</fullName>
            </value>
            <value>
                <fullName>660</fullName>
            </value>
            <value>
                <fullName>010</fullName>
            </value>
            <value>
                <fullName>028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddressISOCodeMap__mdt/AddressISOCodeMap__mdt.object-meta.xml
<CustomObject>
    <label>AddressISOCodeMap</label>
    <pluralLabel>AddressISOCodeMaps</pluralLabel>
</CustomObject>

force-app/main/default/objects/AddressISOCodeMap__mdt/fields/Alpha2__c.field-meta.xml
<CustomField>
    <fullName>Alpha2__c</fullName>
    <label>Alpha2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressISOCodeMap__mdt/fields/Alpha3__c.field-meta.xml
<CustomField>
    <fullName>Alpha3__c</fullName>
    <label>Alpha3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressISOCodeMap__mdt/fields/UN_Code__c.field-meta.xml
<CustomField>
    <fullName>UN_Code__c</fullName>
    <label>UN Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressTriggerHandler.cls
public inherited sharing class AddressTriggerHandler {
    
    public static void getAddress(List<Address__c> addressList){
        List<AddressISOCodeMap__mdt> addressMetaDataList = [Select Id ,label, alpha2__c, alpha3__c, UN_Code__c
                                                                 from AddressISOCodeMap__mdt ];
        for(Address__c addrs : addressList){
            String uniKey = '';
            unikey = addrs.Alpha2__c +addrs.Alpha3__c+ addrs.UN_Code__c;
            for(AddressISOCodeMap__mdt mtdRec : addressMetaDataList ){
                String comKey = '';
                comKey = mtdRec.alpha2__c+mtdRec.alpha3__c+mtdRec.UN_Code__c;
                if(comKey == uniKey){
                    addrs.Country__c = mtdRec.label;
                }
                    
            }

        }
    
    }
}