force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Alpha2__c.field-meta.xml
<CustomField>
    <fullName>Alpha2__c</fullName>
    <label>Alpha2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>DZ</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Alpha3__c.field-meta.xml
<CustomField>
    <fullName>Alpha3__c</fullName>
    <label>Alpha3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Alpha2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFG</fullName>
            </value>
            <value>
                <fullName>ALA</fullName>
            </value>
            <value>
                <fullName>ALB</fullName>
            </value>
            <value>
                <fullName>DZA</fullName>
            </value>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AIA</fullName>
            </value>
            <value>
                <fullName>ATA</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/UN_Code__c.field-meta.xml
<CustomField>
    <fullName>UN_Code__c</fullName>
    <label>UN Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Alpha3__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>248</fullName>
            </value>
            <value>
                <fullName>008</fullName>
            </value>
            <value>
                <fullName>012</fullName>
            </value>
            <value>
                <fullName>016</fullName>
            </value>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>024</fullName>
            </value>
            <value>
                <fullName>660</fullName>
            </value>
            <value>
                <fullName>010</fullName>
            </value>
            <value>
                <fullName>028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddressTriggerHandler_Test.cls
@isTest
public inherited sharing class AddressTriggerHandler_Test {
    @isTest
    public static void testM1(){
        List<Address__c> addList = new List<Address__c>();
        for(integer i =0 ; i < 3 ; i++){
            Address__c rec = new Address__c();
            rec.alpha2__c = 'AD';
            rec.alpha3__c = 'AND';
            rec.UN_Code__c = '020';
            addList.add(rec);
        }
        if(addList.size() > 0){
            insert addList;
        }
        addList[0].alpha2__c = 'AL';
        addList[0].alpha3__c = 'ALB';
        addList[0].UN_Code__c = '008';
        update addList[0];
    }
}